{
    "name": "Deploy docs",
    "on": { "push": { "branches": "main" }},
    "jobs": {
        "update-pages": {
            "runs-on": "ubuntu-latest",
            "container": "fedora-latest",
            "steps": [
                {
                    "name": "Check out code",
                    "uses": "actions/checkout@v2",
                },
                {
                    "name": "Build docs",
                    "run": "./ci/before-docs-deploy.sh",
                },
                {
                    "name": "Deploy latest docs",
                    "uses": "JamesIves/github-pages-deploy-action@releases/v3",
                    "with": {
                        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                        "BRANCH": "gh-pages",
                        "FOLDER": "ci_docs_build/html",
                        "TARGET_FOLDER": "latest",
                    },
                },
            ],
        },
    },
}
